# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/godhead/Desktop/legacy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/godhead/Desktop/legacy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/godhead/Desktop/legacy/CMakeFiles /home/godhead/Desktop/legacy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/godhead/Desktop/legacy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named legacy

# Build rule for target.
legacy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 legacy
.PHONY : legacy

# fast build rule for target.
legacy/fast:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/build
.PHONY : legacy/fast

Protection/main.o: Protection/main.c.o

.PHONY : Protection/main.o

# target to build an object file
Protection/main.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/Protection/main.c.o
.PHONY : Protection/main.c.o

Protection/main.i: Protection/main.c.i

.PHONY : Protection/main.i

# target to preprocess a source file
Protection/main.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/Protection/main.c.i
.PHONY : Protection/main.c.i

Protection/main.s: Protection/main.c.s

.PHONY : Protection/main.s

# target to generate assembly for a file
Protection/main.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/Protection/main.c.s
.PHONY : Protection/main.c.s

bank/term.o: bank/term.c.o

.PHONY : bank/term.o

# target to build an object file
bank/term.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/bank/term.c.o
.PHONY : bank/term.c.o

bank/term.i: bank/term.c.i

.PHONY : bank/term.i

# target to preprocess a source file
bank/term.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/bank/term.c.i
.PHONY : bank/term.c.i

bank/term.s: bank/term.c.s

.PHONY : bank/term.s

# target to generate assembly for a file
bank/term.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/bank/term.c.s
.PHONY : bank/term.c.s

banker_simulation/implementation.o: banker_simulation/implementation.c.o

.PHONY : banker_simulation/implementation.o

# target to build an object file
banker_simulation/implementation.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/banker_simulation/implementation.c.o
.PHONY : banker_simulation/implementation.c.o

banker_simulation/implementation.i: banker_simulation/implementation.c.i

.PHONY : banker_simulation/implementation.i

# target to preprocess a source file
banker_simulation/implementation.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/banker_simulation/implementation.c.i
.PHONY : banker_simulation/implementation.c.i

banker_simulation/implementation.s: banker_simulation/implementation.c.s

.PHONY : banker_simulation/implementation.s

# target to generate assembly for a file
banker_simulation/implementation.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/banker_simulation/implementation.c.s
.PHONY : banker_simulation/implementation.c.s

banker_simulation/main.o: banker_simulation/main.c.o

.PHONY : banker_simulation/main.o

# target to build an object file
banker_simulation/main.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/banker_simulation/main.c.o
.PHONY : banker_simulation/main.c.o

banker_simulation/main.i: banker_simulation/main.c.i

.PHONY : banker_simulation/main.i

# target to preprocess a source file
banker_simulation/main.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/banker_simulation/main.c.i
.PHONY : banker_simulation/main.c.i

banker_simulation/main.s: banker_simulation/main.c.s

.PHONY : banker_simulation/main.s

# target to generate assembly for a file
banker_simulation/main.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/banker_simulation/main.c.s
.PHONY : banker_simulation/main.c.s

management/main.o: management/main.c.o

.PHONY : management/main.o

# target to build an object file
management/main.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/management/main.c.o
.PHONY : management/main.c.o

management/main.i: management/main.c.i

.PHONY : management/main.i

# target to preprocess a source file
management/main.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/management/main.c.i
.PHONY : management/main.c.i

management/main.s: management/main.c.s

.PHONY : management/main.s

# target to generate assembly for a file
management/main.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/management/main.c.s
.PHONY : management/main.c.s

memory-allocator/alloc.o: memory-allocator/alloc.cc.o

.PHONY : memory-allocator/alloc.o

# target to build an object file
memory-allocator/alloc.cc.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/memory-allocator/alloc.cc.o
.PHONY : memory-allocator/alloc.cc.o

memory-allocator/alloc.i: memory-allocator/alloc.cc.i

.PHONY : memory-allocator/alloc.i

# target to preprocess a source file
memory-allocator/alloc.cc.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/memory-allocator/alloc.cc.i
.PHONY : memory-allocator/alloc.cc.i

memory-allocator/alloc.s: memory-allocator/alloc.cc.s

.PHONY : memory-allocator/alloc.s

# target to generate assembly for a file
memory-allocator/alloc.cc.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/memory-allocator/alloc.cc.s
.PHONY : memory-allocator/alloc.cc.s

monte/main.o: monte/main.c.o

.PHONY : monte/main.o

# target to build an object file
monte/main.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/monte/main.c.o
.PHONY : monte/main.c.o

monte/main.i: monte/main.c.i

.PHONY : monte/main.i

# target to preprocess a source file
monte/main.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/monte/main.c.i
.PHONY : monte/main.c.i

monte/main.s: monte/main.c.s

.PHONY : monte/main.s

# target to generate assembly for a file
monte/main.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/monte/main.c.s
.PHONY : monte/main.c.s

stack/stack.o: stack/stack.c.o

.PHONY : stack/stack.o

# target to build an object file
stack/stack.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/stack/stack.c.o
.PHONY : stack/stack.c.o

stack/stack.i: stack/stack.c.i

.PHONY : stack/stack.i

# target to preprocess a source file
stack/stack.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/stack/stack.c.i
.PHONY : stack/stack.c.i

stack/stack.s: stack/stack.c.s

.PHONY : stack/stack.s

# target to generate assembly for a file
stack/stack.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/stack/stack.c.s
.PHONY : stack/stack.c.s

sys/creat.o: sys/creat.c.o

.PHONY : sys/creat.o

# target to build an object file
sys/creat.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/creat.c.o
.PHONY : sys/creat.c.o

sys/creat.i: sys/creat.c.i

.PHONY : sys/creat.i

# target to preprocess a source file
sys/creat.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/creat.c.i
.PHONY : sys/creat.c.i

sys/creat.s: sys/creat.c.s

.PHONY : sys/creat.s

# target to generate assembly for a file
sys/creat.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/creat.c.s
.PHONY : sys/creat.c.s

sys/lseek.o: sys/lseek.c.o

.PHONY : sys/lseek.o

# target to build an object file
sys/lseek.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/lseek.c.o
.PHONY : sys/lseek.c.o

sys/lseek.i: sys/lseek.c.i

.PHONY : sys/lseek.i

# target to preprocess a source file
sys/lseek.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/lseek.c.i
.PHONY : sys/lseek.c.i

sys/lseek.s: sys/lseek.c.s

.PHONY : sys/lseek.s

# target to generate assembly for a file
sys/lseek.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/lseek.c.s
.PHONY : sys/lseek.c.s

sys/open.o: sys/open.c.o

.PHONY : sys/open.o

# target to build an object file
sys/open.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/open.c.o
.PHONY : sys/open.c.o

sys/open.i: sys/open.c.i

.PHONY : sys/open.i

# target to preprocess a source file
sys/open.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/open.c.i
.PHONY : sys/open.c.i

sys/open.s: sys/open.c.s

.PHONY : sys/open.s

# target to generate assembly for a file
sys/open.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/open.c.s
.PHONY : sys/open.c.s

sys/read.o: sys/read.c.o

.PHONY : sys/read.o

# target to build an object file
sys/read.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/read.c.o
.PHONY : sys/read.c.o

sys/read.i: sys/read.c.i

.PHONY : sys/read.i

# target to preprocess a source file
sys/read.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/read.c.i
.PHONY : sys/read.c.i

sys/read.s: sys/read.c.s

.PHONY : sys/read.s

# target to generate assembly for a file
sys/read.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/read.c.s
.PHONY : sys/read.c.s

sys/truncate.o: sys/truncate.c.o

.PHONY : sys/truncate.o

# target to build an object file
sys/truncate.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/truncate.c.o
.PHONY : sys/truncate.c.o

sys/truncate.i: sys/truncate.c.i

.PHONY : sys/truncate.i

# target to preprocess a source file
sys/truncate.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/truncate.c.i
.PHONY : sys/truncate.c.i

sys/truncate.s: sys/truncate.c.s

.PHONY : sys/truncate.s

# target to generate assembly for a file
sys/truncate.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/truncate.c.s
.PHONY : sys/truncate.c.s

sys/write.o: sys/write.c.o

.PHONY : sys/write.o

# target to build an object file
sys/write.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/write.c.o
.PHONY : sys/write.c.o

sys/write.i: sys/write.c.i

.PHONY : sys/write.i

# target to preprocess a source file
sys/write.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/write.c.i
.PHONY : sys/write.c.i

sys/write.s: sys/write.c.s

.PHONY : sys/write.s

# target to generate assembly for a file
sys/write.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/sys/write.c.s
.PHONY : sys/write.c.s

tele++/main.o: tele++/main.cpp.o

.PHONY : tele++/main.o

# target to build an object file
tele++/main.cpp.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/tele++/main.cpp.o
.PHONY : tele++/main.cpp.o

tele++/main.i: tele++/main.cpp.i

.PHONY : tele++/main.i

# target to preprocess a source file
tele++/main.cpp.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/tele++/main.cpp.i
.PHONY : tele++/main.cpp.i

tele++/main.s: tele++/main.cpp.s

.PHONY : tele++/main.s

# target to generate assembly for a file
tele++/main.cpp.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/tele++/main.cpp.s
.PHONY : tele++/main.cpp.s

ticketing_sys/main.o: ticketing_sys/main.c.o

.PHONY : ticketing_sys/main.o

# target to build an object file
ticketing_sys/main.c.o:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/ticketing_sys/main.c.o
.PHONY : ticketing_sys/main.c.o

ticketing_sys/main.i: ticketing_sys/main.c.i

.PHONY : ticketing_sys/main.i

# target to preprocess a source file
ticketing_sys/main.c.i:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/ticketing_sys/main.c.i
.PHONY : ticketing_sys/main.c.i

ticketing_sys/main.s: ticketing_sys/main.c.s

.PHONY : ticketing_sys/main.s

# target to generate assembly for a file
ticketing_sys/main.c.s:
	$(MAKE) -f CMakeFiles/legacy.dir/build.make CMakeFiles/legacy.dir/ticketing_sys/main.c.s
.PHONY : ticketing_sys/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... legacy"
	@echo "... edit_cache"
	@echo "... Protection/main.o"
	@echo "... Protection/main.i"
	@echo "... Protection/main.s"
	@echo "... bank/term.o"
	@echo "... bank/term.i"
	@echo "... bank/term.s"
	@echo "... banker_simulation/implementation.o"
	@echo "... banker_simulation/implementation.i"
	@echo "... banker_simulation/implementation.s"
	@echo "... banker_simulation/main.o"
	@echo "... banker_simulation/main.i"
	@echo "... banker_simulation/main.s"
	@echo "... management/main.o"
	@echo "... management/main.i"
	@echo "... management/main.s"
	@echo "... memory-allocator/alloc.o"
	@echo "... memory-allocator/alloc.i"
	@echo "... memory-allocator/alloc.s"
	@echo "... monte/main.o"
	@echo "... monte/main.i"
	@echo "... monte/main.s"
	@echo "... stack/stack.o"
	@echo "... stack/stack.i"
	@echo "... stack/stack.s"
	@echo "... sys/creat.o"
	@echo "... sys/creat.i"
	@echo "... sys/creat.s"
	@echo "... sys/lseek.o"
	@echo "... sys/lseek.i"
	@echo "... sys/lseek.s"
	@echo "... sys/open.o"
	@echo "... sys/open.i"
	@echo "... sys/open.s"
	@echo "... sys/read.o"
	@echo "... sys/read.i"
	@echo "... sys/read.s"
	@echo "... sys/truncate.o"
	@echo "... sys/truncate.i"
	@echo "... sys/truncate.s"
	@echo "... sys/write.o"
	@echo "... sys/write.i"
	@echo "... sys/write.s"
	@echo "... tele++/main.o"
	@echo "... tele++/main.i"
	@echo "... tele++/main.s"
	@echo "... ticketing_sys/main.o"
	@echo "... ticketing_sys/main.i"
	@echo "... ticketing_sys/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

